name       : perl-file-homedir
version    : '1.006'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/File-HomeDir-1.006.tar.gz : 593737c62df0f6dab5d4122e0b4476417945bb6262c33eedc009665ef1548852
license    :
    - Artistic-1.0
    - GPL-2.0-or-later
homepage   : https://metacpan.org/pod/File::HomeDir
component  : programming.perl
summary    : Find your home and other directories on any platform
description: |
    File::HomeDir is a module for locating the directories that are "owned" by a user (typically your user) and to solve the various issues that arise trying to find them consistently across a wide variety of platforms.
builddeps  :
    - perl-file-which # Testing
rundeps    :
    - perl-file-which
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
